### PR TITLE
Minor refactor

### PR DESCRIPTION
**Pull request by krishna-kashyap**
Hi,

While going through the code, thinking about ways of adding support for partitioned databases, found some small changes that could make code more consistent. Not sure if this would help, have tried to keep the logic undisturbed, moving stuff around, tried to make it a bit more idiomatic maybe (with the little rust I know)

### CODE REVIEW

**Comment by krishna-kashyap** [comment]
I verified the tests passing, but the doc-tests seem to fail on all integration tests. I see them fail on the master also. Not sure if those are expected to pass.

**Comment by krishna-kashyap** [comment]
Okay, so it turned out to be the issue with running it on Alpine which needs slightly different set of build variables since we use OpenSSL by default here. Ran it on a x86_64 setup and now all tests are passing.

**Comment by mibes** [comment]
Thanks for your contribution. I've merged it in the "develop" branch.

**Comment by krishna-kashyap** [comment]
Thank you, apologies I didn't see the develop branch earlier.

**Pull request merged**
